#!/bin/bash
###############################################################################
# This script delete all the temporary files generated by remote hadoop
# processes.
#
# You give it the file with the list of hadoop slaves and it uses ssh
# to remove all hadoop related files under /tmp created with your username.
# E.g.
#
#	./rm-hadoop-tmp-files.sh hadoop-0.20.2/conf/slaves
#
###############################################################################

usage="Script needs slaves file. [USAGE]: $(basename "$0") slaves_file"

# Print usage if no file is given
if [[ $# -eq 0 ]] ; then
    echo $usage
    exit 0
fi

# Load list of hostnames into a HOST_LIST array
IFS=$'\r\n' GLOBIGNORE='*' command eval 'HOST_LIST=($(cat $1))'

stop-all.sh

# Iterate over every hostname in the list and delete the hadoop generated
# temporary files under the current username
for host in "${HOST_LIST[@]}"
do
    echo "=========== Deleting Hadoop temp files on: $host ==========="
    ssh -t $USER@$host 'echo "user: $USER";\
        find /tmp -maxdepth 1 -regex ".*\(hadoop\|hsperfdata\).*" -group $USER -exec rm -rfv {} \;'
done
